import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar ported from the previous mkdocs `nav:` tree, preserving order and
 * nesting. Doc ids are file paths under docs/ without the .md extension.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'about/introduction',
        'about/installation',
        'about/getting-started',
        'guide/configuration',
        'about/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      link: {type: 'doc', id: 'cli/index'},
      items: [
        {
          type: 'category',
          label: 'Objects',
          items: [
            'cli/objects/auto-tag-action',
            'cli/objects/address',
            'cli/objects/address-group',
            'cli/objects/application',
            'cli/objects/application-filter',
            'cli/objects/application-group',
            'cli/objects/dynamic-user-group',
            'cli/objects/external-dynamic-list',
            'cli/objects/hip-object',
            'cli/objects/hip-profile',
            'cli/objects/http-server-profile',
            'cli/objects/log-forwarding-profile',
            'cli/objects/quarantined-device',
            'cli/objects/region',
            'cli/objects/schedule',
            'cli/objects/service',
            'cli/objects/service-group',
            'cli/objects/syslog-server-profile',
            'cli/objects/tag',
            'cli/objects/sdk-objects',
          ],
        },
        {
          type: 'category',
          label: 'Network',
          items: [
            'cli/network/aggregate-interface',
            'cli/network/bgp-address-family-profile',
            'cli/network/bgp-auth-profile',
            'cli/network/bgp-filtering-profile',
            'cli/network/bgp-redistribution-profile',
            'cli/network/bgp-route-map',
            'cli/network/bgp-route-map-redistribution',
            'cli/network/dhcp-interface',
            'cli/network/ethernet-interface',
            'cli/network/ike-crypto-profile',
            'cli/network/ike-gateway',
            'cli/network/ipsec-crypto-profile',
            'cli/network/layer2-subinterface',
            'cli/network/layer3-subinterface',
            'cli/network/loopback-interface',
            'cli/network/nat-rule',
            'cli/network/qos-profile',
            'cli/network/ospf-auth-profile',
            'cli/network/route-access-list',
            'cli/network/route-prefix-list',
            'cli/network/security-zone',
            'cli/network/tunnel-interface',
            'cli/network/vlan-interface',
            'cli/network/sdk-network',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            'cli/security/anti-spyware-profile',
            'cli/security/app-override-rule',
            'cli/security/authentication-rule',
            'cli/security/decryption-profile',
            'cli/security/decryption-rule',
            'cli/security/dns-security-profile',
            'cli/security/rules',
            'cli/security/url-access-profile',
            'cli/security/url-category',
            'cli/security/vulnerability-protection-profile',
            'cli/security/wildfire-antivirus-profile',
            'cli/security/sdk-security',
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          items: [
            'cli/deployment/bandwidth',
            'cli/deployment/bgp-routing',
            'cli/deployment/internal-dns-server',
            'cli/deployment/network-location',
            'cli/deployment/remote-network',
            'cli/deployment/service-connection',
            'cli/deployment/sdk-deployment',
          ],
        },
        {
          type: 'category',
          label: 'Setup',
          items: [
            'cli/setup/device',
            'cli/setup/folder',
            'cli/setup/label',
            'cli/setup/snippet',
            'cli/setup/variable',
            'cli/setup/sdk-setup',
          ],
        },
        {
          type: 'category',
          label: 'Identity',
          items: [
            'cli/identity/authentication-profile',
            'cli/identity/kerberos-server-profile',
            'cli/identity/ldap-server-profile',
            'cli/identity/radius-server-profile',
            'cli/identity/saml-server-profile',
            'cli/identity/tacacs-server-profile',
          ],
        },
        {
          type: 'category',
          label: 'Mobile Agent',
          items: [
            'cli/mobile-agent/agent-version',
            'cli/mobile-agent/agent-profile',
            'cli/mobile-agent/auth-setting',
            'cli/mobile-agent/forwarding-profile',
            'cli/mobile-agent/forwarding-profile-destination',
            'cli/mobile-agent/forwarding-profile-regional-and-custom-proxy',
            'cli/mobile-agent/forwarding-profile-source-application',
            'cli/mobile-agent/forwarding-profile-user-location',
            'cli/mobile-agent/tunnel-profile',
            'cli/mobile-agent/global-setting',
            'cli/mobile-agent/infrastructure-setting',
            'cli/mobile-agent/sdk-mobile-agent',
          ],
        },
        {
          type: 'category',
          label: 'Local Config',
          items: ['cli/local/index'],
        },
        {
          type: 'category',
          label: 'Operations',
          items: ['cli/operations/index'],
        },
        {
          type: 'category',
          label: 'Incidents',
          items: ['cli/incidents/index'],
        },
        'cli/jobs',
        'cli/commit',
        'cli/insights',
        'cli/posture',
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        'guide/getting-started',
        'guide/configuration',
        'guide/configuration-objects',
        'guide/advanced-topics',
        'guide/data-models',
        'guide/operations',
        'guide/ai-agents',
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: ['about/release-notes', 'about/contributing', 'about/license'],
    },
  ],
};

export default sidebars;
